# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookStore_CarlosNeto' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BookStore_CarlosNeto
  pod "AFNetworking", "~> 2.0"

end
